#
# Module manifest for module 'Vester'
#
# Generated by: Brian Bunke
#
# Generated on: 8/28/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSAzureAudit.psm1'

# Version number of this module.
ModuleVersion = '0.1.0'

# ID used to uniquely identify this module
GUID = 'e6341674-0c74-47f1-9740-ef9d63734c67'

# Author of this module
Author = 'r3dLiN3'

# Company or vendor of this module
CompanyName = 'Community'

# Copyright statement for this module
Copyright = 'MIT License'

# Description of the functionality provided by this module
Description = 'Check your VMware vSphere environment for undesired values, and automatically fix them. Define settings, then use PowerCLI and Pester to report on and/or remediate any problems discovered.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    @{ModuleName = 'Pester'; ModuleVersion = '4.3.1'},
    @{ModuleName = 'Azure'; ModuleVersion = '5.5.1'},
    @{ModuleName = 'AzureRM.Profile'; ModuleVersion = '4.3.1'},
    @{ModuleName = 'AzureRM.Storage'; ModuleVersion = '3.2.1'}
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
#FormatsToProcess = @('PSAzureAudit.Format.ps1xml')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @(
    'Invoke-AzureAudit',
    'New-AzureAuditTest',
    'New-AzureAuditConfig'
)

# Cmdlets to export from this module
# CmdletsToExport = '*'

# Variables to export from this module
# VariablesToExport = '*'

# Aliases to export from this module
# AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('azure','audit','CSI')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/r3dlin3/PSAzureAudit/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/r3dlin3/PSAzureAudit/'

        # A URL to an icon representing this module.
        # IconUri = ''

        # External Module Dependencies
        # ExternalModuleDependencies = @()

        # ReleaseNotes of this module
        ReleaseNotes = 'https://github.com/r3dlin3/PSAzureAudit/blob/master/CHANGELOG.adoc'
    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
