= PSAzureAudit

This module intents to implement all controls present in the  
https://www.cisecurity.org/cis-microsoft-azure-foundations-benchmark-v1-0-0-now-available/[CIS Microsoft Azure Foundations Benchmark v1.0.0 Now Available].

This module is inspired by https://github.com/WahlNetwork/Vester[Vester].

It is built on top of https://github.com/pester/Pester[Pester] and Azure Powershell

For now, remediation will not be the priority.

== PSAzureAudit vs. Chef InSpec

I anticipate that all information will not be available through the resource manager API. 
It is the case for access level of containers in Storage Accounts.

Moreover, I want a solution able to scan all resources and not one in particular or one resource group.

== PSAzureAudit vs. Azure Policy

Azure Policy is not extensible.

Azure Policy does not implement or do not allow to implement all controls.


== Support

The community module is not officially supported and should be used at your own risk.

To report a bug, request an enhancement, or provide feedback about this project, please open an issue.


== Wishlist

1) To be able to use default tests and to use custom tests
